### ISSUE TITLE
Google OAuth Offline Access?

### ISSUE THREAD

**Issue by sgarbesi** [fangli/kibana-authentication-proxy#10]
Thanks for the Auth proxy; awesome.

Everytime I login via Google OAuth it keeps requesting permission for Offline Access? Bug? I would think this should be a one and done.

Aside from that no complaints.

Feature idea: Force SSL?

**Comment by fangli** [comment]
Bug of OAuth fixed.
If you want to force SSL, you can just block the non-ssl port by iptables or firewall.
