### ISSUE TITLE
Doesn't work with express 4 - set version to < 4 or upgrade?

### ISSUE THREAD

**Issue by nicobrevin** [fangli/kibana-authentication-proxy#11]
I've just done a fresh install, and on `node app.js` I get:

<pre>
Server starting...

/home/nickg/src/kibana-authentication-proxy/app.js:20
app.use(express.cookieParser());
                ^
TypeError: Object function createApplication() {
  var app = function(req, res, next) {
    app.handle(req, res, next);
  };

  mixin(app, proto);
  mixin(app, EventEmitter.prototype);

  app.request = { __proto__: req, app: app };
  app.response = { __proto__: res, app: app };
  app.init();
  return app;
} has no method 'cookieParser'
    at Object.<anonymous> (/home/nickg/src/kibana-authentication-proxy/app.js:20:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
</pre>

**Comment by fangli** [comment]
Hi maybe it doesn't compatible with expressjs 4.
But at this moment I won't move on to expressjs4 because a few libraries still don't support as well.

**Comment by nicobrevin** [comment]
Correct, so I think you just need to set the version in your package dot
json so newbies like me don't get flustered!

**Comment by fangli** [comment]
Sorry for that the bugs didn't happen until expressjs released 4.0.0rc1 just 4 days ago...
Anyhow I should specific the version as you said in package.js, thanks for the remind.

**Comment by nicobrevin** [comment]
Hehe, no problem!

**Comment by fangli** [comment]
Fixed.

**Comment by fangli** [comment]
If still stuck here, please "git pull", delete the folder ./node_modules/, and run "npm install" again.
