### ISSUE TITLE
Cant start node app.js

### ISSUE THREAD

**Issue by romankor** [fangli/kibana-authentication-proxy#12]
I have completed the installation instructions. But still getting some error when starting to start the node app.

Here is my 'npm list'

kibana-authentication-proxy@1.1.0 /opt/kibana-authentication-proxy
├── cas@0.0.3
├── connect-restreamer@1.0.0
├─┬ express@4.0.0-rc2
│ ├─┬ accepts@1.0.0
│ │ ├── mime@1.2.11
│ │ └── negotiator@0.3.0
│ ├── buffer-crc32@0.2.1
│ ├── cookie@0.1.0
│ ├── cookie-signature@1.0.3
│ ├── debug@0.7.4
│ ├── escape-html@1.0.1
│ ├── fresh@0.2.2
│ ├── merge-descriptors@0.0.2
│ ├── methods@0.1.0
│ ├── qs@0.6.6
│ ├── range-parser@1.0.0
│ ├─┬ send@0.2.0
│ │ └── mime@1.2.11
│ ├─┬ type-is@1.0.0
│ │ └── mime@1.2.11
│ └── utils-merge@1.0.0
├─┬ passport@0.2.0
│ ├── passport-strategy@1.0.0
│ └── pause@0.0.1
└─┬ passport-google-oauth@0.1.5
  ├─┬ passport-oauth@0.1.15
  │ ├── oauth@0.9.11
  │ └─┬ passport@0.1.18
  │   └── pause@0.0.1
  └── pkginfo@0.2.3

root@ip-10-67-146-75:/opt/kibana-authentication-proxy# node app.js
Server starting...

/opt/kibana-authentication-proxy/app.js:20
app.use(express.cookieParser());
                ^
TypeError: Object function createApplication() {
  var app = function(req, res, next) {
    app.handle(req, res, next);
  };

  mixin(app, proto);
  mixin(app, EventEmitter.prototype);

  app.request = { **proto**: req, app: app };
  app.response = { **proto**: res, app: app };
  app.init();
  return app;
} has no method 'cookieParser'
    at Object.<anonymous> (/opt/kibana-authentication-proxy/app.js:20:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

Thanks

**Comment by fangli** [comment]
Hi the issue has been fixed.

See https://github.com/fangli/kibana-authentication-proxy/issues/11
Let me know if it doesn't work.

**Comment by romankor** [comment]
Indeed that fixes it
