### ISSUE TITLE
Application Crashing When Refresh Button Clicked

### ISSUE THREAD

**Issue by ebiven** [fangli/kibana-authentication-proxy#13]
On a page load the proxy works fine, and it may work fine on a handful of refreshes from within Kibana. However it will always eventually crash the app and give the following dump:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketOnEnd [as onend] (http.js:1568:23)
    at Socket.g (events.js:180:16)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

The kibana-authentication-proxy is running behind an Nginx proxy that is doing SSL termination and forwarding from port 443 to port 9201 on the server running kibana-authentication-proxy. It exhibits the same problem with basic and Google OAuth authentication.

When the kibana-authentication-proxy is accessed directly from a browser (bypassing the Nginx proxy and SSL) it doesn't exhibit this problem, but we have the same Nginx proxy functioning with multiple other node apps and not experiencing these behaviors.

**Comment by fangli** [comment]
Maybe it's a bug,
check later

Thanks:)

**Comment by fangli** [comment]
Hi, please git pull and try again.

**Comment by ebiven** [comment]
Sorry, not ignoring you, just been incredibly busy. I'll try and test it out next week.

**Comment by fangli** [comment]
No hurry, just take your time
