### ISSUE TITLE
CAS V2

### ISSUE THREAD

**Issue by ABalanuta** [fangli/kibana-authentication-proxy#14]
Hi there,

I experience the same problem as in the closed issue "Fix CAS bug auth with express version 3.4.8"

My question is: Does it suport CAS v2 ?

**Comment by fangli** [comment]
CAS v2 is more complicate than v1, I suppose, No.
Moreover, I can't find any npm library that support v2.

**Comment by fangli** [comment]
If you could find one, pls tell me. It's not difficult to integrate with it.

**Comment by ABalanuta** [comment]
ok, will try

**Comment by fangli** [comment]
Thank you:)
I'll close this issue if you have further questions create a new one.
