### ISSUE TITLE
LDAP config

### ISSUE THREAD

**Issue by karnamonkster** [fangli/kibana-authentication-proxy#16]
Hi,

Is there anyway we could have it used with LDAP credentials.

**Comment by fangli** [comment]
Hi,

LDAP is a professional but cumbersome protocol that out of my schedule, thus I'll keep it away in the near future.
But it's not a hard work to integrate it with kibana auth proxy, since Nodejs has many third-party LDAP modules, you may wanna try it by yourself.

Hope you can understand.

**Comment by karnamonkster** [comment]
Ok thanks a lot
