### ISSUE TITLE
temp shared dashboards should live in global kibana index

### ISSUE THREAD

**Issue by faxm0dem** [fangli/kibana-authentication-proxy#7]
the per-user kibana index is great, but has one culprit: it's not possible to share temporary dashboards anymore, as they are ironically being saved in the per-user index.

Proposed change:

have a setting for global index (defaulting to kibana-int)
and save temps in there

**Comment by johnnye** [comment]
@faxm0dem see this fork https://github.com/johnnye/kibana-authentication-proxy/ of the project where I'm doing organisation wide kibana dashboards.

**Comment by fangli** [comment]
@faxm0dem It's definitely a side-effect that can not share dashboards anymore, but I really don't want to involve the original kibana too much, especially when kibana3 is under active development stage. it's just designed for authentication and work as a wrapper.

As a quick workaround, you can launch multiple nodejs instances on different ports, or you can also save the shared dashboard to the local and import them to some sort of public account.

Or you can take a look on @johnnye 's fork as well and he is working on this.

**Comment by faxm0dem** [comment]
I'm not sure what you mean by "the original kibana"

**Comment by fangli** [comment]
@faxm0dem I mean project "kibana3" itself.
That how to save and share dashboards, is managed by kibana3 itself, and I don't want to meddle with it. it's just a little out of bounds for a _authentication proxy_.

**Comment by faxm0dem** [comment]
I understand this, and it's sane to want to keep this simple to allow easy maintenance of a rapidly changing kibana project. This being said, I still think this change is in the scope of accepted #5.

Of course I'll look into the  fork of @johnnye and/or fork the project myself if you don't agree.

**Comment by faxm0dem** [comment]
Ok so I guess that means you don't agree

**Comment by fangli** [comment]
@faxm0dem I agree with you but I really don't have enough time to get it done since there is no good solutions on this problem.
Why not follow johnnye's fork:)

**Comment by faxm0dem** [comment]
I understand, np
