### ISSUE TITLE
Error in install - Error: failed to fetch from registry: connect-restreamer

### ISSUE THREAD

**Issue by galindro** [fangli/kibana-authentication-proxy#8]
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/passport
npm http GET https://registry.npmjs.org/passport-google-oauth
npm http GET https://registry.npmjs.org/connect-restreamer
npm http GET https://registry.npmjs.org/cas

npm ERR! Error: failed to fetch from registry: connect-restreamer
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /var/www/kibana-authentication-proxy/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-58-virtual
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/kibana-authentication-proxy
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: connect-restreamer
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/kibana-authentication-proxy/npm-debug.log
npm not ok

My System:
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.4 LTS
Release:    12.04
Codename:   precise

**Comment by fangli** [comment]
I'm pretty sure it's related to the npm or your network rather than kibana-authentication-proxy.
Please try again with:

```
# npm update
```

If error persistents, ask help from the nodejs/npm community:)

**Comment by galindro** [comment]
Even after npm update, the error persists, but now, with another package:

``` bash
# npm update
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/passport
npm http GET https://registry.npmjs.org/passport-google-oauth
npm http GET https://registry.npmjs.org/connect-restreamer
npm http GET https://registry.npmjs.org/cas

# npm install
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/passport
npm http GET https://registry.npmjs.org/passport-google-oauth
npm http GET https://registry.npmjs.org/connect-restreamer
npm http GET https://registry.npmjs.org/cas

npm ERR! Error: failed to fetch from registry: passport
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /var/www/kibana-authentication-proxy/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-58-virtual
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/kibana-authentication-proxy
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: passport
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/kibana-authentication-proxy/npm-debug.log
npm not ok

```

I'll talk with nodejs/npm community as you sugested.

Tks!

**Comment by fangli** [comment]
Well since you have another package failure, I think it's related to your network.
make sure you have a good connection when npm update, and I suggest you try "npm update" multi times until all necessary node packages been installed.

**Comment by galindro** [comment]
Solved by doind this:

``` bash
npm config set registry http://registry.npmjs.org/
apt-get install -y python-software-properties python g++ make
add-apt-repository ppa:chris-lea/node.js
apt-get update && apt-get install nodejs
npm update
npm install
```

**Comment by wrathchylde** [comment]
Thank you! The npm fix you posted was my exact problem. So glad you took the time to follow on.

**Comment by galindro** [comment]
Nice! :)

**Comment by LinderTech** [comment]
thanks!
